version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "true"

    ports:
      - "3307:3306"              # host 3307 -> container 3306 (Docker MySQL)
    volumes:
      - mysql_data:/var/lib/mysql

  kafka:
    image: apache/kafka:latest  #docker pull bitnami/kafka:latest

    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_KRAFT_CLUSTER_ID: "kafka-cluster-1"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  app:
    image: aagezai/employee-service:1.0
    depends_on:
      - mysql
      - kafka
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/mydb
      spring.datasource.username: root
      spring.datasource.password: secret
      spring.kafka.bootstrap-servers: kafka:9092
    ports:
      - "8080:8080"

volumes:
  mysql_data:
  kafka_data:
